services:
  - type: web
    name: restaurant-app
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/restaurantapp-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_HOME
        value: /opt/render/project/java/openjdk17
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d118d1qdbo4c739nctq0-a.oregon-postgres.render.com:5432/restaurantdb_gu3s
      - key: SPRING_DATASOURCE_USERNAME
        value: restaurant_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: nEAnbVr5ossn8yNxN9ClYCk2vHrlPlmh
