services:
  - type: web
    name: restaurant-app
    plan: free
    environment: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: postgresql://restaurant_user:nEAnbVr5ossn8yNxN9ClYCk2vHrlPlmh@dpg-d1l8d1qdbo4c739nctq0-a/restaurantdb_gu3s
#    envVars:
#      - key: DB_HOST
#        value: dpg-d1l8d1qdbo4c739nctq0-a.render.com
#      - key: DB_PORT
#        value: 5432
#      - key: DATASOURCE_BASE
#        value: restaurantdb_gu3s
#      - key: DATABASE_USER
#        value: restaurant_user
#      - key: DATABASE_PASSWORD
#        value: nEAnbVr5ossn8yNxN9ClYCk2vHrlPlmh