services:
  - type: web
    name: restaurant-app
    plan: free
    environment: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d118d1qdbo4c739nctq0-a.oregon-postgres.render.com:5432/restaurantdb_gu3s
      - key: SPRING_DATASOURCE_USERNAME
        value: restaurant_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: nEAnbVr5ossn8yNxN9ClYCk2vHrlPlmh