services:
  - type: web
    name: restaurant-app
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/RestaurantApp-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_HOME
        value: /opt/render/project/java/openjdk17